third_party_settings:
  shortcut:
    module_link: true
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://BP.jpeg'
favicon:
  use_default: true
